spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/timescape
    username: timescape
    password: "@25991"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  web:
    resources:
      static-locations: file:upload
jwt:
  secret: ab77c860-5327-40bc-9cd1-9ac2372fa77a
  expiration: 3600000
  expiration-refresh: 86400000
storage:
  location: upload